version: "3.4"
services:
  wol-service:
    container_name: wol-service
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    ports:
      - "3000:3000"
    restart: always
